create table user_messages
(
    user_id            TEXT,
    guild_id           TEXT,
    word_counter       INTEGER,
    attachment_counter INTEGER,
    timestamp          INTEGER
);

create table user_voice
(
    user_id      TEXT,
    guild_id     TEXT,
    time_counter INTEGER,
    timestamp    INTEGER
);

create table white_lists
(
    guild_id   TEXT,
    channel_id TEXT,
    constraint table_name_pk
        unique (guild_id, channel_id) on conflict ignore
);
