name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Libraries install
      run: |
        sudo apt install libopus0
        sudo apt install wget
        wget -O dpp.deb https://dl.dpp.dev/
        sudo dpkg -i dpp.deb
        rm dpp.deb
        sudo apt install libspdlog-dev
        cd lib
        git submodule init
        git submodule update
        cd ..
        cd lib/SQLiteCpp
        cmake -B ./build
        cmake --build ./build -j8
        cd build
        sudo make install
        cd ..
        rm -r build
        cd ..

    - name: Build
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        cmake --build ${{github.workspace}}/build -j8 --config ${{env.BUILD_TYPE}}
        cd build
        make
        cd ..
      
    - name: Export
      uses: actions/upload-artifact@v4
      with:
        name: export-binaries
        path: build

